# Generated by Django 5.0.6 on 2024-06-04 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_plan", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classschedule",
            name="class_time",
        ),
        migrations.AddField(
            model_name="classschedule",
            name="end_time",
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name="classschedule",
            name="start_time",
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name="testschedule",
            name="test_end",
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name="testschedule",
            name="test_start",
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name="assignmentdeadline",
            name="assignment_due_date",
            field=models.DateTimeField(),
        ),
    ]
