# Generated by Django 5.0.6 on 2024-06-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_plan", "0002_remove_classschedule_class_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classschedule",
            name="class_day",
            field=models.CharField(
                choices=[
                    ("MON", "Monday"),
                    ("TUE", "Tuesday"),
                    ("WED", "Wednesday"),
                    ("THU", "Thursday"),
                    ("FRI", "Friday"),
                    ("SAT", "Saturday"),
                    ("SUN", "Sunday"),
                ],
                default="Monday",
                max_length=3,
            ),
            preserve_default=False,
        ),
    ]
