# Generated by Django 5.0.6 on 2024-06-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_plan", "0004_alter_classschedule_options_courseplan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classschedule",
            name="end_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="classschedule",
            name="start_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="testschedule",
            name="test_end",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="testschedule",
            name="test_start",
            field=models.TimeField(),
        ),
    ]
