# Generated by Django 5.0.6 on 2024-05-30 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField()),
                ('sets', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('training_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FitnessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(max_length=255)),
                ('fitness_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_plan.fitnessplan')),
            ],
        ),
        migrations.CreateModel(
            name='SessionPlanTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitness_plan.customization')),
                ('session_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_plan.sessionplan')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_plan.training')),
            ],
            options={
                'unique_together': {('session_plan', 'training')},
            },
        ),
        migrations.AddField(
            model_name='sessionplan',
            name='trainings',
            field=models.ManyToManyField(through='fitness_plan.SessionPlanTraining', to='fitness_plan.training'),
        ),
    ]
