# Generated by Django 5.0.6 on 2024-05-31 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fitness_plan", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sessionplan",
            name="trainings",
        ),
    ]
