# Generated by Django 5.0.6 on 2024-06-03 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_plan', '0003_rename_sessionplantraining_sessiontraining'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sessiontraining',
            unique_together=set(),
        ),
    ]
