# Generated by Django 5.0.6 on 2024-06-08 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_plan", "0001_initial"),
        ("fitness_plan", "0004_alter_sessiontraining_unique_together"),
        ("main", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityplan",
            name="course_plan",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="course_plan.courseplan"
            ),
        ),
        migrations.AlterField(
            model_name="activityplan",
            name="fitness_plan",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="fitness_plan.fitnessplan",
            ),
        ),
        migrations.AlterField(
            model_name="activityplan",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
