# Generated by Django 5.0.6 on 2024-07-12 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_plan', '0004_alter_sessiontraining_unique_together'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityplan',
            name='fitness_plan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitness_plan.fitnessplan'),
        ),
    ]
